spring.application.name=stockpilotai-backend

server.port=5455

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/stockpilotai
spring.datasource.username= root
spring.datasource.password= shivaJ@123